version: "3.9"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: logstream
      POSTGRES_PASSWORD: logstream
      POSTGRES_DB: logs
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  redis_data:
  pg_data:
