spring.application.name=log-api
spring.datasource.url=jdbc:postgresql://localhost:5432/logdb
spring.datasource.username=loguser
spring.datasource.password=logpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

